// <auto-generated />
using System;
using KLTN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KLTN.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607031548_UpdateThanhToanNavigationProperties")]
    partial class UpdateThanhToanNavigationProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KLTN.Models.Database.BangLuongPT", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThangNam")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongHoaHong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaPT");

                    b.ToTable("BangLuongPTs");
                });

            modelBuilder.Entity("KLTN.Models.Database.BaoCaoTaiChinh", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiLap")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("NguoiLap");

                    b.ToTable("BaoCaoTaiChinhs");
                });

            modelBuilder.Entity("KLTN.Models.Database.CapNhatAnhNhanDien", b =>
                {
                    b.Property<int>("MaCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCapNhat"));

                    b.Property<byte[]>("AnhCu")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("AnhMoi")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCapNhat");

                    b.HasIndex("MaTK");

                    b.HasIndex("NguoiCapNhat");

                    b.ToTable("CapNhatAnhNhanDiens");
                });

            modelBuilder.Entity("KLTN.Models.Database.DangKy", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiDangKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaGoiTap")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachVangLai")
                        .HasColumnType("int");

                    b.Property<int?>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaTV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoBuoi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaGoiTap");

                    b.HasIndex("MaKhachVangLai");

                    b.HasIndex("MaLopHoc");

                    b.HasIndex("MaTV");

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("KLTN.Models.Database.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("GiaBatDau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiDichVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaGoiTap")
                        .HasColumnType("int");

                    b.Property<int?>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDichVu");

                    b.HasIndex("MaGoiTap")
                        .IsUnique()
                        .HasFilter("[MaGoiTap] IS NOT NULL");

                    b.HasIndex("MaLopHoc")
                        .IsUnique()
                        .HasFilter("[MaLopHoc] IS NOT NULL");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("KLTN.Models.Database.GiaHanDangKy", b =>
                {
                    b.Property<int>("MaGiaHan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaHan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<int?>("MaTKNguoiThu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGiaHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThucMoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoBuoiThem")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TaiKhoanMaTK")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaGiaHan");

                    b.HasIndex("MaDangKy");

                    b.HasIndex("MaTKNguoiThu");

                    b.HasIndex("TaiKhoanMaTK");

                    b.ToTable("GiaHanDangKys");
                });

            modelBuilder.Entity("KLTN.Models.Database.GoiTap", b =>
                {
                    b.Property<int>("MaGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoi"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaKM")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SoLanTapToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiHanThang")
                        .HasColumnType("int");

                    b.HasKey("MaGoi");

                    b.HasIndex("MaKM");

                    b.ToTable("GoiTap");
                });

            modelBuilder.Entity("KLTN.Models.Database.HuanLuyenVien", b =>
                {
                    b.Property<int>("MaPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPT"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThaiHLV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPT");

                    b.HasIndex("MaTK")
                        .IsUnique();

                    b.ToTable("HuanLuyenViens");
                });

            modelBuilder.Entity("KLTN.Models.Database.KhachVangLai", b =>
                {
                    b.Property<int>("MaKVL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKVL"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayGhiNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKVL");

                    b.ToTable("KhachVangLais");
                });

            modelBuilder.Entity("KLTN.Models.Database.KhuyenMai", b =>
                {
                    b.Property<int>("MaKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKM"));

                    b.Property<string>("DoiTuongApDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GiaTriToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDaSuDung")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongMaToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("KLTN.Models.Database.LichSuCheckIn", b =>
                {
                    b.Property<int>("MaCheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCheckIn"));

                    b.Property<byte[]>("AnhNhanDien")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("KetQuaNhanDien")
                        .HasColumnType("bit");

                    b.Property<int?>("MaKVL")
                        .HasColumnType("int");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int");

                    b.Property<int?>("ThanhVienMaTV")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCheckIn");

                    b.HasIndex("MaKVL");

                    b.HasIndex("MaTK");

                    b.HasIndex("ThanhVienMaTV");

                    b.ToTable("LichSuCheckIns");
                });

            modelBuilder.Entity("KLTN.Models.Database.LichSuDangKy", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaGoi")
                        .HasColumnType("int");

                    b.Property<int>("MaTV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaGoi");

                    b.HasIndex("MaTV");

                    b.ToTable("LichSuDangKy");
                });

            modelBuilder.Entity("KLTN.Models.Database.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaPT")
                        .HasColumnType("int");

                    b.Property<string>("NgayTrongTuan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuongHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaPT");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("KLTN.Models.Database.PT_PhanCongHoaHong", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<int?>("MaGoiTap")
                        .HasColumnType("int");

                    b.Property<int?>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaPT")
                        .HasColumnType("int");

                    b.Property<decimal>("PhanTramHoaHong")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaGoiTap");

                    b.HasIndex("MaLopHoc");

                    b.HasIndex("MaPT", "MaGoiTap")
                        .IsUnique()
                        .HasFilter("[MaGoiTap] IS NOT NULL");

                    b.HasIndex("MaPT", "MaLopHoc")
                        .IsUnique()
                        .HasFilter("[MaLopHoc] IS NOT NULL");

                    b.ToTable("PT_PhanCongHoaHongs");
                });

            modelBuilder.Entity("KLTN.Models.Database.PhienDay", b =>
                {
                    b.Property<int>("MaPhienDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhienDay"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiaTriBuoiDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiDichVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiPhienDay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaBangLuong")
                        .HasColumnType("int");

                    b.Property<int?>("MaGoiTap")
                        .HasColumnType("int");

                    b.Property<int?>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaPT")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhienDay");

                    b.HasIndex("MaBangLuong");

                    b.HasIndex("MaGoiTap");

                    b.HasIndex("MaLopHoc");

                    b.HasIndex("MaPT");

                    b.ToTable("PhienDays");
                });

            modelBuilder.Entity("KLTN.Models.Database.PhienTap", b =>
                {
                    b.Property<int>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhien"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaKhachVangLai")
                        .HasColumnType("int");

                    b.Property<int?>("MaPT")
                        .HasColumnType("int");

                    b.Property<int?>("MaThanhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhien");

                    b.HasIndex("MaKhachVangLai");

                    b.HasIndex("MaPT");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("PhienTap");
                });

            modelBuilder.Entity("KLTN.Models.Database.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("KLTN.Models.Database.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTK");

                    b.HasIndex("MaQuyen");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("KLTN.Models.Database.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<bool>("DaXuatHoaDon")
                        .HasColumnType("bit");

                    b.Property<string>("DonViThanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoaDonDienTuUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<int?>("MaGiaHan")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaKVL_NguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaTKNguoiThu")
                        .HasColumnType("int");

                    b.Property<int?>("MaTK_NguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDung_KhachVangLaiMaKVL")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDung_TaiKhoanMaTK")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaiKhoanThanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDangKy");

                    b.HasIndex("MaGiaHan");

                    b.HasIndex("MaTKNguoiThu");

                    b.HasIndex("NguoiDung_KhachVangLaiMaKVL");

                    b.HasIndex("NguoiDung_TaiKhoanMaTK");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("KLTN.Models.Database.ThanhVien", b =>
                {
                    b.Property<int>("MaTV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTV"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaTV");

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.ToTable("ThanhViens");
                });

            modelBuilder.Entity("KLTN.Models.Database.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThanhVienMaTV")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaTK");

                    b.HasIndex("ThanhVienMaTV");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("KLTN.Models.Database.TinTuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuc"));

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnhURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDang")
                        .HasColumnType("int");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TacGiaDisplay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("NguoiDang");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("KLTN.Models.Database.BangLuongPT", b =>
                {
                    b.HasOne("KLTN.Models.Database.HuanLuyenVien", "HuanLuyenVien")
                        .WithMany("BangLuongPTs")
                        .HasForeignKey("MaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuanLuyenVien");
                });

            modelBuilder.Entity("KLTN.Models.Database.BaoCaoTaiChinh", b =>
                {
                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithMany("BaoCaoTaiChinhsLap")
                        .HasForeignKey("NguoiLap");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.CapNhatAnhNhanDien", b =>
                {
                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithMany("AnhNhanDienDuocCapNhat")
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLTN.Models.Database.TaiKhoan", "NguoiCapNhatTaiKhoan")
                        .WithMany("CapNhatAnhNhanDienThucHien")
                        .HasForeignKey("NguoiCapNhat")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiCapNhatTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.DangKy", b =>
                {
                    b.HasOne("KLTN.Models.Database.GoiTap", "GoiTap")
                        .WithMany("DangKys")
                        .HasForeignKey("MaGoiTap");

                    b.HasOne("KLTN.Models.Database.KhachVangLai", "KhachVangLai")
                        .WithMany("DangKys")
                        .HasForeignKey("MaKhachVangLai");

                    b.HasOne("KLTN.Models.Database.LopHoc", "LopHoc")
                        .WithMany("DangKys")
                        .HasForeignKey("MaLopHoc");

                    b.HasOne("KLTN.Models.Database.ThanhVien", "ThanhVien")
                        .WithMany("DangKys")
                        .HasForeignKey("MaTV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");

                    b.Navigation("KhachVangLai");

                    b.Navigation("LopHoc");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("KLTN.Models.Database.DichVu", b =>
                {
                    b.HasOne("KLTN.Models.Database.GoiTap", "GoiTap")
                        .WithOne("DichVu")
                        .HasForeignKey("KLTN.Models.Database.DichVu", "MaGoiTap");

                    b.HasOne("KLTN.Models.Database.LopHoc", "LopHoc")
                        .WithOne("DichVu")
                        .HasForeignKey("KLTN.Models.Database.DichVu", "MaLopHoc");

                    b.Navigation("GoiTap");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("KLTN.Models.Database.GiaHanDangKy", b =>
                {
                    b.HasOne("KLTN.Models.Database.DangKy", "DangKy")
                        .WithMany("GiaHanDangKys")
                        .HasForeignKey("MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KLTN.Models.Database.TaiKhoan", "NguoiThu")
                        .WithMany("GiaHanDangKysLap")
                        .HasForeignKey("MaTKNguoiThu");

                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanMaTK");

                    b.Navigation("DangKy");

                    b.Navigation("NguoiThu");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.GoiTap", b =>
                {
                    b.HasOne("KLTN.Models.Database.KhuyenMai", "KhuyenMai")
                        .WithMany("GoiTaps")
                        .HasForeignKey("MaKM");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("KLTN.Models.Database.HuanLuyenVien", b =>
                {
                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithOne("HuanLuyenVien")
                        .HasForeignKey("KLTN.Models.Database.HuanLuyenVien", "MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.LichSuCheckIn", b =>
                {
                    b.HasOne("KLTN.Models.Database.KhachVangLai", "KhachVangLai")
                        .WithMany("LichSuCheckIns")
                        .HasForeignKey("MaKVL");

                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK");

                    b.HasOne("KLTN.Models.Database.ThanhVien", null)
                        .WithMany("LichSuCheckIns")
                        .HasForeignKey("ThanhVienMaTV");

                    b.Navigation("KhachVangLai");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.LichSuDangKy", b =>
                {
                    b.HasOne("KLTN.Models.Database.GoiTap", "GoiTap")
                        .WithMany("LichSuDangKys")
                        .HasForeignKey("MaGoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KLTN.Models.Database.ThanhVien", "ThanhVien")
                        .WithMany("LichSuDangKys")
                        .HasForeignKey("MaTV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("KLTN.Models.Database.LopHoc", b =>
                {
                    b.HasOne("KLTN.Models.Database.HuanLuyenVien", "HuanLuyenVien")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaPT");

                    b.Navigation("HuanLuyenVien");
                });

            modelBuilder.Entity("KLTN.Models.Database.PT_PhanCongHoaHong", b =>
                {
                    b.HasOne("KLTN.Models.Database.GoiTap", "GoiTap")
                        .WithMany("PT_PhanCongHoaHongs")
                        .HasForeignKey("MaGoiTap");

                    b.HasOne("KLTN.Models.Database.LopHoc", "LopHoc")
                        .WithMany("PT_PhanCongHoaHongs")
                        .HasForeignKey("MaLopHoc");

                    b.HasOne("KLTN.Models.Database.HuanLuyenVien", "HuanLuyenVien")
                        .WithMany("PT_PhanCongHoaHongs")
                        .HasForeignKey("MaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");

                    b.Navigation("HuanLuyenVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("KLTN.Models.Database.PhienDay", b =>
                {
                    b.HasOne("KLTN.Models.Database.BangLuongPT", "BangLuongPT")
                        .WithMany("PhienDaysTrongKyLuong")
                        .HasForeignKey("MaBangLuong");

                    b.HasOne("KLTN.Models.Database.GoiTap", "GoiTap")
                        .WithMany("PhienDays")
                        .HasForeignKey("MaGoiTap");

                    b.HasOne("KLTN.Models.Database.LopHoc", "LopHoc")
                        .WithMany("PhienDays")
                        .HasForeignKey("MaLopHoc");

                    b.HasOne("KLTN.Models.Database.HuanLuyenVien", "HuanLuyenVien")
                        .WithMany("PhienDays")
                        .HasForeignKey("MaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangLuongPT");

                    b.Navigation("GoiTap");

                    b.Navigation("HuanLuyenVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("KLTN.Models.Database.PhienTap", b =>
                {
                    b.HasOne("KLTN.Models.Database.KhachVangLai", "KhachVangLai")
                        .WithMany("PhienTaps")
                        .HasForeignKey("MaKhachVangLai");

                    b.HasOne("KLTN.Models.Database.HuanLuyenVien", "HuanLuyenVien")
                        .WithMany()
                        .HasForeignKey("MaPT");

                    b.HasOne("KLTN.Models.Database.ThanhVien", "ThanhVien")
                        .WithMany("PhienTaps")
                        .HasForeignKey("MaThanhVien");

                    b.Navigation("HuanLuyenVien");

                    b.Navigation("KhachVangLai");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("KLTN.Models.Database.TaiKhoan", b =>
                {
                    b.HasOne("KLTN.Models.Database.Quyen", "Quyen")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("KLTN.Models.Database.ThanhToan", b =>
                {
                    b.HasOne("KLTN.Models.Database.DangKy", "DangKy")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDangKy");

                    b.HasOne("KLTN.Models.Database.GiaHanDangKy", "GiaHanDangKy")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaGiaHan");

                    b.HasOne("KLTN.Models.Database.TaiKhoan", "NguoiThu")
                        .WithMany("ThanhToansLap")
                        .HasForeignKey("MaTKNguoiThu");

                    b.HasOne("KLTN.Models.Database.KhachVangLai", "NguoiDung_KhachVangLai")
                        .WithMany()
                        .HasForeignKey("NguoiDung_KhachVangLaiMaKVL");

                    b.HasOne("KLTN.Models.Database.TaiKhoan", "NguoiDung_TaiKhoan")
                        .WithMany()
                        .HasForeignKey("NguoiDung_TaiKhoanMaTK");

                    b.Navigation("DangKy");

                    b.Navigation("GiaHanDangKy");

                    b.Navigation("NguoiDung_KhachVangLai");

                    b.Navigation("NguoiDung_TaiKhoan");

                    b.Navigation("NguoiThu");
                });

            modelBuilder.Entity("KLTN.Models.Database.ThanhVien", b =>
                {
                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithOne("ThanhVien")
                        .HasForeignKey("KLTN.Models.Database.ThanhVien", "MaTK");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.ThongBao", b =>
                {
                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithMany("ThongBaosGui")
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KLTN.Models.Database.ThanhVien", null)
                        .WithMany("ThongBaos")
                        .HasForeignKey("ThanhVienMaTV");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.TinTuc", b =>
                {
                    b.HasOne("KLTN.Models.Database.TaiKhoan", "TaiKhoan")
                        .WithMany("TinTucsDang")
                        .HasForeignKey("NguoiDang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLTN.Models.Database.BangLuongPT", b =>
                {
                    b.Navigation("PhienDaysTrongKyLuong");
                });

            modelBuilder.Entity("KLTN.Models.Database.DangKy", b =>
                {
                    b.Navigation("GiaHanDangKys");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("KLTN.Models.Database.GiaHanDangKy", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("KLTN.Models.Database.GoiTap", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("DichVu");

                    b.Navigation("LichSuDangKys");

                    b.Navigation("PT_PhanCongHoaHongs");

                    b.Navigation("PhienDays");
                });

            modelBuilder.Entity("KLTN.Models.Database.HuanLuyenVien", b =>
                {
                    b.Navigation("BangLuongPTs");

                    b.Navigation("LopHocs");

                    b.Navigation("PT_PhanCongHoaHongs");

                    b.Navigation("PhienDays");
                });

            modelBuilder.Entity("KLTN.Models.Database.KhachVangLai", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("LichSuCheckIns");

                    b.Navigation("PhienTaps");
                });

            modelBuilder.Entity("KLTN.Models.Database.KhuyenMai", b =>
                {
                    b.Navigation("GoiTaps");
                });

            modelBuilder.Entity("KLTN.Models.Database.LopHoc", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("DichVu");

                    b.Navigation("PT_PhanCongHoaHongs");

                    b.Navigation("PhienDays");
                });

            modelBuilder.Entity("KLTN.Models.Database.Quyen", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("KLTN.Models.Database.TaiKhoan", b =>
                {
                    b.Navigation("AnhNhanDienDuocCapNhat");

                    b.Navigation("BaoCaoTaiChinhsLap");

                    b.Navigation("CapNhatAnhNhanDienThucHien");

                    b.Navigation("GiaHanDangKysLap");

                    b.Navigation("HuanLuyenVien");

                    b.Navigation("ThanhToansLap");

                    b.Navigation("ThanhVien");

                    b.Navigation("ThongBaosGui");

                    b.Navigation("TinTucsDang");
                });

            modelBuilder.Entity("KLTN.Models.Database.ThanhVien", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("LichSuCheckIns");

                    b.Navigation("LichSuDangKys");

                    b.Navigation("PhienTaps");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
