// <auto-generated />
using System;
using GymManagement.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagement.Web.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20250812051928_AddMissingDiemDanhColumns")]
    partial class AddMissingDiemDanhColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagement.Web.Data.Models.BangLuong", b =>
                {
                    b.Property<int>("BangLuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BangLuongId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("HlvId")
                        .HasColumnType("int");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("Thang")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<decimal>("TienHoaHong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("BangLuongId");

                    b.HasIndex("HlvId");

                    b.ToTable("BangLuongs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LichLopId")
                        .HasColumnType("int");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayDat")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThanhVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BOOKED");

                    b.HasKey("BookingId");

                    b.HasIndex("LichLopId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.BuoiHlv", b =>
                {
                    b.Property<int>("BuoiHlvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuoiHlvId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("HlvId")
                        .HasColumnType("int");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayTap")
                        .HasColumnType("date");

                    b.Property<int?>("ThanhVienId")
                        .HasColumnType("int");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("int");

                    b.HasKey("BuoiHlvId");

                    b.HasIndex("HlvId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("BuoiHlvs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.BuoiTap", b =>
                {
                    b.Property<int>("BuoiTapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuoiTapId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int");

                    b.Property<int?>("ThanhVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianVao")
                        .HasColumnType("datetime2");

                    b.HasKey("BuoiTapId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("BuoiTaps");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.CauHinhHoaHong", b =>
                {
                    b.Property<int>("CauHinhHoaHongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHinhHoaHongId"));

                    b.Property<int?>("GoiTapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhanTramHoaHong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CauHinhHoaHongId");

                    b.HasIndex("GoiTapId");

                    b.ToTable("CauHinhHoaHongs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.DangKy", b =>
                {
                    b.Property<int>("DangKyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyId"));

                    b.Property<int?>("GoiTapId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiDangKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhiDangKy")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("TrangThaiChiTiet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DangKyId");

                    b.HasIndex("GoiTapId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.DiemDanh", b =>
                {
                    b.Property<int>("DiemDanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiemDanhId"));

                    b.Property<string>("AnhMinhChung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("DoTinCay")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("KetQuaNhanDang")
                        .HasColumnType("bit");

                    b.Property<int?>("LichLopId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiCheckIn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ThanhVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ThoiGianCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DiemDanhId");

                    b.HasIndex("LichLopId");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ExternalLogin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaiKhoanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("ExternalLogins", (string)null);
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.GoiTap", b =>
                {
                    b.Property<int>("GoiTapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoiTapId"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SoBuoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiHanThang")
                        .HasColumnType("int");

                    b.HasKey("GoiTapId");

                    b.ToTable("GoiTaps");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.KhuyenMai", b =>
                {
                    b.Property<int>("KhuyenMaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhuyenMaiId"));

                    b.Property<bool>("KichHoat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.HasKey("KhuyenMaiId");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.KhuyenMaiUsage", b =>
                {
                    b.Property<int>("KhuyenMaiUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhuyenMaiUsageId"));

                    b.Property<int?>("DangKyId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KhuyenMaiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySuDung")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienCuoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ThanhToanId")
                        .HasColumnType("int");

                    b.HasKey("KhuyenMaiUsageId");

                    b.HasIndex("DangKyId");

                    b.HasIndex("KhuyenMaiId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("ThanhToanId");

                    b.ToTable("KhuyenMaiUsages");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LichLop", b =>
                {
                    b.Property<int>("LichLopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichLopId"));

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<int>("SoLuongDaDat")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("SCHEDULED");

                    b.HasKey("LichLopId");

                    b.HasIndex("LopHocId");

                    b.ToTable("LichLops");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LichSuAnh", b =>
                {
                    b.Property<int>("LichSuAnhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichSuAnhId"));

                    b.Property<string>("AnhCu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AnhMoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("LichSuAnhId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LichSuAnhs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LopHoc", b =>
                {
                    b.Property<int>("LopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocId"));

                    b.Property<decimal?>("GiaTuyChinh")
                        .HasColumnType("decimal(12,2)");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int?>("HlvId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiDangKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayBatDauKhoa")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThucKhoa")
                        .HasColumnType("date");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThuTrongTuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("OPEN");

                    b.HasKey("LopHocId");

                    b.HasIndex("HlvId");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.MauMat", b =>
                {
                    b.Property<int>("MauMatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MauMatId"));

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("ThuatToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ArcFace");

                    b.HasKey("MauMatId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("MauMats");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungId"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiNguoiDung")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgayThamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("NguoiDungId");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.TaiKhoan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailXacNhan")
                        .HasColumnType("bit");

                    b.Property<bool>("KichHoat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NguoiDungId")
                        .IsUnique()
                        .HasFilter("[NguoiDungId] IS NOT NULL");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.TaiKhoanVaiTro", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TaiKhoanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VaiTroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VaiTroId");

                    b.HasIndex("TaiKhoanId", "VaiTroId")
                        .IsUnique();

                    b.ToTable("TaiKhoanVaiTros", (string)null);
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"));

                    b.Property<int?>("DangKyId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("DangKyId");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ThanhToanGateway", b =>
                {
                    b.Property<int>("GatewayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GatewayId"));

                    b.Property<decimal?>("GatewayAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("GatewayMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GatewayOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayRespCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GatewayTen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("VNPAY");

                    b.Property<string>("GatewayTransId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThanhToanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCallback")
                        .HasColumnType("datetime2");

                    b.HasKey("GatewayId");

                    b.HasIndex("ThanhToanId")
                        .IsUnique();

                    b.ToTable("ThanhToanGateways");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ThongBao", b =>
                {
                    b.Property<int>("ThongBaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongBaoId"));

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Kenh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThongBaoId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.TinTuc", b =>
                {
                    b.Property<int>("TinTucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TinTucId"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayXuatBan")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("TenTacGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DRAFT");

                    b.HasKey("TinTucId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.HasIndex("TacGiaId");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.VaiTro", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.BangLuong", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "Hlv")
                        .WithMany("BangLuongs")
                        .HasForeignKey("HlvId");

                    b.Navigation("Hlv");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.Booking", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.LichLop", "LichLop")
                        .WithMany("Bookings")
                        .HasForeignKey("LichLopId");

                    b.HasOne("GymManagement.Web.Data.Models.LopHoc", "LopHoc")
                        .WithMany("Bookings")
                        .HasForeignKey("LopHocId");

                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "ThanhVien")
                        .WithMany("Bookings")
                        .HasForeignKey("ThanhVienId");

                    b.Navigation("LichLop");

                    b.Navigation("LopHoc");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.BuoiHlv", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "Hlv")
                        .WithMany("BuoiHlvs")
                        .HasForeignKey("HlvId");

                    b.HasOne("GymManagement.Web.Data.Models.LopHoc", "LopHoc")
                        .WithMany("BuoiHlvs")
                        .HasForeignKey("LopHocId");

                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "ThanhVien")
                        .WithMany("BuoiHlvThanhViens")
                        .HasForeignKey("ThanhVienId");

                    b.Navigation("Hlv");

                    b.Navigation("LopHoc");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.BuoiTap", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.LopHoc", "LopHoc")
                        .WithMany("BuoiTaps")
                        .HasForeignKey("LopHocId");

                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "ThanhVien")
                        .WithMany("BuoiTaps")
                        .HasForeignKey("ThanhVienId");

                    b.Navigation("LopHoc");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.CauHinhHoaHong", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.GoiTap", "GoiTap")
                        .WithMany("CauHinhHoaHongs")
                        .HasForeignKey("GoiTapId");

                    b.Navigation("GoiTap");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.DangKy", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.GoiTap", "GoiTap")
                        .WithMany("DangKys")
                        .HasForeignKey("GoiTapId");

                    b.HasOne("GymManagement.Web.Data.Models.LopHoc", "LopHoc")
                        .WithMany("DangKys")
                        .HasForeignKey("LopHocId");

                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany("DangKys")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.DiemDanh", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.LichLop", "LichLop")
                        .WithMany()
                        .HasForeignKey("LichLopId");

                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "ThanhVien")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("ThanhVienId");

                    b.Navigation("LichLop");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ExternalLogin", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.KhuyenMaiUsage", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.DangKy", "DangKy")
                        .WithMany()
                        .HasForeignKey("DangKyId");

                    b.HasOne("GymManagement.Web.Data.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagement.Web.Data.Models.ThanhToan", "ThanhToan")
                        .WithMany()
                        .HasForeignKey("ThanhToanId");

                    b.Navigation("DangKy");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NguoiDung");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LichLop", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.LopHoc", "LopHoc")
                        .WithMany("LichLops")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LichSuAnh", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuAnhs")
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LopHoc", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "Hlv")
                        .WithMany("LopHocs")
                        .HasForeignKey("HlvId");

                    b.Navigation("Hlv");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.MauMat", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "NguoiDung")
                        .WithOne("MauMat")
                        .HasForeignKey("GymManagement.Web.Data.Models.MauMat", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.TaiKhoan", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("GymManagement.Web.Data.Models.TaiKhoan", "NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.TaiKhoanVaiTro", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("TaiKhoanVaiTros")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagement.Web.Data.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoanVaiTros")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ThanhToan", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.DangKy", "DangKy")
                        .WithMany("ThanhToans")
                        .HasForeignKey("DangKyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DangKy");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ThanhToanGateway", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.ThanhToan", "ThanhToan")
                        .WithOne("ThanhToanGateway")
                        .HasForeignKey("GymManagement.Web.Data.Models.ThanhToanGateway", "ThanhToanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ThongBao", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.TinTuc", b =>
                {
                    b.HasOne("GymManagement.Web.Data.Models.NguoiDung", "TacGia")
                        .WithMany()
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.DangKy", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.GoiTap", b =>
                {
                    b.Navigation("CauHinhHoaHongs");

                    b.Navigation("DangKys");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LichLop", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.LopHoc", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("BuoiHlvs");

                    b.Navigation("BuoiTaps");

                    b.Navigation("DangKys");

                    b.Navigation("LichLops");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.NguoiDung", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("Bookings");

                    b.Navigation("BuoiHlvThanhViens");

                    b.Navigation("BuoiHlvs");

                    b.Navigation("BuoiTaps");

                    b.Navigation("DangKys");

                    b.Navigation("DiemDanhs");

                    b.Navigation("LichSuAnhs");

                    b.Navigation("LopHocs");

                    b.Navigation("MauMat");

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.TaiKhoan", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("TaiKhoanVaiTros");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.ThanhToan", b =>
                {
                    b.Navigation("ThanhToanGateway");
                });

            modelBuilder.Entity("GymManagement.Web.Data.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoanVaiTros");
                });
#pragma warning restore 612, 618
        }
    }
}
